### ISSUE TITLE
Não completa a compra

### ISSUE THREAD

**Issue by LuizSantos22** [gumnet/magento-1-ame-digital-integration#1]
Olá,
Fiz a integração e não funcionou.

Condições para a reprodução do problema:

1 - Baixe e instale a fork do Magento 1.9 (OpenMage 1.9.4.15): https://github.com/OpenMage/magento-lts/releases

2 - Tenha no servidor a versão PHP 7.2 ou 7.3

3 - Instale o plugin da GumNet: https://github.com/gumnet/magento-1-ame-digital-integration

4 - Seguindo o tutorial: https://gum.net.br/wp-content/uploads/2020/07/PassoapassoAMEconfigMAGENTO1.pdf

5 - Criação dos tokens usando a conta AmeDigital: https://minhaconta.amedigital.com/integracao/magento-1-9

6 - Simule a compra, o pedido finaliza, mas não ocorre a geração do QR Code da Ame

No tutorial da Ame, há uma informação que não consegui compreender: 
"Magento 1.9
Antes de iniciar o passo a passo, garanta que tenha realizado as seguintes ações:
Envio de IP de saída do website à Ame, para liberação." 

O que seria "IP de saída do site"? E como enviar isso à Ame para a liberação? 
Em nenhum momento a Ame explica como obter este "IP de saída" e também não diz como informar isso
a eles. 

Nos formulários de contato, sequer há a opção integração. 

Espero que consigam resolver o problema, pq gostaria bastante de ter essa solução no meu site.

**Comment by gustavoulyssea** [comment]
Olá Luiz,

Tudo bom ? 

Este é um caso de suporte técnico da instalação que pode necessitar de seus dados. Estamos numa área pública para reportar de erros no desenvolvimento. Poderia enviar um email para suporte@gum.net.br para analisarmos por favor ?

Muito obrigado!

Atenciosamente,
Gustavo Ulyssea
