### ISSUE TITLE
Compra não gera QR Code e não concretiza.

### ISSUE THREAD

**Issue by LuizSantos22** [gumnet/magento-1-ame-digital-integration#2]
Desculpe voltar a relatar o mesmo problema
https://github.com/gumnet/magento-1-ame-digital-integration/issues/1

Mas eu enviei um e-mail para: suporte@gum.net.br no dia 22/11 e outro no dia 23/11
e não obtive resposta. 

Eu gostaria realmente de usar este plugin, e o suporte da Ame também não me apresenta
qualquer solução para o problema.

Att
Luiz Santos

**Comment by gustavoulyssea** [comment]
Estranho, Luiz, realmente não chegou o email aqui. Faz um grande favor envia pro meu email pessoal gustavo.ulyssea@gmail.com... não sei se o filtro de SPAM agiu aí... Obrigado!!
